version: "3.9"

services:
  neutralisation-api:
    image: alexis-turintech/gender-neutralisation
    container_name: gender-neutralisation-api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: on-failure
    depends_on:
      neutralisation-redis:
        condition: service_healthy
    networks:
      - neutralisation

  neutralisation-redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: "redis-cli PING"
      interval: 2s
      retries: 10
    networks:
      - neutralisation

volumes:
  redis_data:
    driver: local

networks:
  neutralisation:
