version: "3.9"

services:
  neutralisation-api:
    image: alexis-turintech/gender-neutralisation
    container_name: gender-neutralisation-api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: on-failure
